version: "3.8"

services:
    web:
        image: fast-api-app
        ports:
            - "8000:8000"
        depends_on:
            - redis
        networks:
            - app-network

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
